disabled_rules:
  - closing_brace
  - trailing_whitespace
  - type_name
  - variable_name
  - valid_docs
excluded:
  - Carthage
force_cast: warning # implicitly
force_try:
    severity: warning # explicitly
line_length: 128
type_body_length:
  - 100 # warning
  - 200 # error
function_body_length:
  - 30 # warning
  - 50 # error
variable_name:
  max_length:
    warning: 60
    error: 80
  min_length:
    warning: 1
